# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Setup kubernetes config from github secret
      - name: Get build secrets
        id: get_build_secret
        run: |
          echo "${{ secrets.CLIENT_INFO }}" > config/client-info.yml

      - name: Setup Kubernetes Tools
        uses: yokawasa/action-setup-kube-tools@v0.9.3
        with:
          setup-tools: |
            kubectl
      # Setup kubernetes config from github secret
      - name: Get secret
        id: get_secret
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yml
      - name: Create namespace
        run: |
          kubectl --kubeconfig='kubeconfig.yml' create ns synology-csi | true
      - name: Build and deploy
        uses: cedrickring/golang-action@1.6.0
        with:
          args: scripts/deploy.sh
        env:
          KUBECONFIG: ./kubeconfig.yml
          IMAGE_TAG:




